version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "upload-data-web"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/upload-img
    networks:
      - app-upload-network
    ports:
      - "8000:8000"
    working_dir: /upload-img
    command: php artisan serv --host 0.0.0.0 --port 8000

networks:
  app-upload-network:
    driver: bridge

volumes:
  dbdata-upload:
    driver: local
